### PR TITLE
Mostly cleaning up W_MarkerMode

### PR DESCRIPTION
**Pull request by gerrievanzyl**
AJ, 
I removed those autosave file and this is what I hope to be the final clean up of the Marker widget.

In the future I want to create separate branches for different issues that I am working on - e.g. one for makers and one to fix bugs.  Unfortunately, this branch is all mixed up in that regard.

The most important thing to apply your mind to are the changes at line 380 of InterfaceHub.pde. Those are the changes relating to the duplicate sdCardStart(sdSetting).  These changes resolved many of the issues with the SD card and the board freezing for me.  I cannot see how sending multiple sdCardStart(sdSetting) would adversely impact the board but it seemed to.  (Is the Electron Hub possibly 'stateful' in a way that gets messed up by multiple sdCardStart(sdSetting) commands?)

If you can pull what you feel valuable from this into your development branch then I can close this branch down.

### CODE REVIEW

**Comment by gerrievanzyl** [comment]
BTW what causes this " //<>//"  in the files?

**Comment by andrewjaykeller** [comment]
> These changes resolved many of the issues with the SD card and the board freezing for me. 

Hey so i think a big problem you are having is not merging in code correctly. If you look at my development branch, most of the code changes you have made have already been resolved. For example `sdCardStart` is called one time, but when you merged in the code, it looked as if `sdCardStart` was called twice and caused you a bunch of problems.

**Comment by andrewjaykeller** [comment]
I tried to resolve these conflicts but idk why it's not working

**Comment by gerrievanzyl** [comment]
To help me understand ....

The sdCardStart  was originally at position A

I forked the code with sdCardStart in A

You changed  sdCardStart to position B

I merged you new code which brought the code into position B while it was
already in position A?

This would also explain the other things (like changing your W_Digitalxxx
files) you were frustrated about when I was pretty sure I did no such thing.

So, how do I fix it?

Was the problem that I started with OpenBCI/OpenBCI_GUI/development?

Sounds like I should start with aj-ptw/OpenBCI_GUI/development?

Thanks for helping me here........

**Comment by gerrievanzyl** [comment]
So, I deleted my features/UDPmarkers branch

To get the latest, must I

   1. fork your aj-ptw/OpenBCI_GUI/development
   2. try to merge (pull) your  aj-ptw/OpenBCI_GUI/development into
   gerrievanzyl/OpenBCI/development
   3. something else?

**Comment by andrewjaykeller** [comment]
>The sdCardStart  was originally at position A
> I forked the code with sdCardStart in A

You changed the code of sdCardStart in A

> You changed  sdCardStart to position B
I removed A and added B

> I merged you new code which brought the code into position B while it was
already in position A?

Yes!

> So, how do I fix it?

I will generally commit the files I want, and then if i need to merge in code that may mess up the code i have that's not committed, I will stash the changes, which cleans the stray code, then i do a pull of the changes which I will resolve any merge conflicts at that point. Let me know which part of this is confusing and I can talk more about it.

**Pull request merged**
